name: "Github Versioned Release"
description: "Github action for creating versioned Github releases containing only the files you want"
author: "Teun Mooij"
branding:
  icon: box
  color: yellow
inputs:
  version:
    description: "The version of the release"
    required: false
  template:
    description: "The template to use for the release"
    required: false
  include:
    description: "The files to include in the release"
    required: false
  exclude:
    description: "The files to exclude from the release"
    required: false
outputs:
  sha:
    description: "The sha of the release"
runs:
  using: "node20"
  main: "dist/index.js"
